apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-nginx-cert
  namespace: istio-system
spec:
  secretName: test-nginx-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - test.foltz.io
